# Generated by Django 3.0.8 on 2020-07-18 10:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_log_entry_audit.models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("app_label", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("fields", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "status",
                    enumfields.fields.EnumField(
                        enum=django_log_entry_audit.models.StatusEnum, max_length=1
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True,
                        related_name="log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Log Entry", "verbose_name_plural": "Log Entries"},
        ),
    ]
