# Generated by Django 3.0.8 on 2020-09-03 07:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django_log_entry_audit.encoders


class Migration(migrations.Migration):

    dependencies = [
        ("django_log_entry_audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="fields",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                encoder=django_log_entry_audit.encoders.JSONEncoder
            ),
        ),
    ]
